# pyproject.toml (FINAL, VERIFIED WORKING VERSION)

[tool.poetry]
name = "automl-agent-crew"
version = "0.1.0"
description = "A 27-agent AutoML and monitoring crew built with CrewAI."
authors = ["Akash Vishnu <akashvishnu6680@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"

# CrewAI (latest available on PyPI)
crewai = "^0.33.4"

# LangChain compatibility
langchain = "0.2.15"
langchain-community = "0.2.14"

# Supporting libs
pydantic = ">=2.5,<3.0"
python-dotenv = "^1.0"
imaplib2 = "^2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
