# pyproject.toml

[tool.poetry]
name = "automl-agent-crew"
version = "0.1.0"
description = "A 27-agent AutoML and monitoring crew built with CrewAI."
authors = ["Akash Vishnu <akashvishnu6680@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
# Set the project's Python version to exactly what the workflow uses (3.11)
python = "^3.11" 

# Ensure Pydantic is explicitly constrained to a version known to work with 3.11 
# and the current CrewAI, which often requires Pydantic V2.
crewai = ">=0.30"
crewai-tools = ">=0.12"
langchain = ">=0.1"
langchain-community = ">=0.1"
pydantic = ">=2.0,<3.0" # Constrain Pydantic to version 2
python-dotenv = ">=1.0"
imaplib2 = "^2.5" 


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
