# pyproject.toml (FINAL, VERIFIED STABLE VERSION V0.2+)

[tool.poetry]
name = "automl-agent-crew"
version = "0.1.0"
description = "A 27-agent AutoML and monitoring crew built with CrewAI."
authors = ["Akash Vishnu <akashvishnu6680@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"

# CrewAI (includes crewai-tools)
crewai = "^0.34"

# LangChain compatibility pair
langchain = "0.2.15"
langchain-community = "0.2.14"

# Supporting libs
pydantic = ">=2.5,<3.0"
python-dotenv = "^1.0"
imaplib2 = "^2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
