name: Scheduled Monitoring and AutoML Crew (AutoGen)

on:
  # Schedule: Runs the workflow every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  run_data_science_crew:
    runs-on: ubuntu-latest
    
    # Define environment variables needed by the Python script
    env:
      # INJECT SECRETS FOR IMAP CONNECTION
      IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
      IMAP_PORT: ${{ secrets.IMAP_PORT }}
      IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
      IMAP_APP_PASSWORD: ${{ secrets.IMAP_PASSWORD }} # Ensure this matches your secret name

      # INJECT SECRETS FOR COMMUNICATION/MOCK
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      
      # INJECT SECRETS FOR GITHUB TOOL
      CREW_COMMIT_TOKEN: ${{ secrets.CREW_COMMIT_TOKEN }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # We stick to a stable Python version
        python-version: '3.11'

    - name: Install dependencies (Pip Install)
      run: |
        # CRITICAL FIX: Install autogen with the [openai] extra dependency 
        # to ensure the LLM client is correctly set up.
        pip install "autogen[openai]>=0.2.14" python-dotenv pydantic requests imaplib2
        
    - name: Run Data Science Crew (AutoGen)
      run: |
        # Execute the main autogen script
        python autogen_workflow.py
